### ISSUE TITLE
Avoid raising exception upon failure

### ISSUE THREAD

**Issue by hgani** [the-refinery/sparkpost_rails#20]
Hi,

I'd like to propose that we don't raise an exception in SparkPostRails::DeliveryMethod#process_result()

```
    def process_result result
      result_data = JSON.parse(result.body)

      if result_data["errors"]
        @response = result_data["errors"]
        raise SparkPostRails::DeliveryException, @response
      else
        @response = result_data["results"]
      end
    end
```

The reason is that this might not work well if we're sending to multiple recipients. For example, if we are sending to 100 recipients, of which 1 of them produces an error. If we raise an exception in this case, this could result in unexpected behaviour.

Particularly, if we use a background worker such as sidekiq, sidekiq will attempt to retry the execution and we might end up resending the same email to those 99 recipients again.

So my suggestion is that we don't raise an exception and instead we recommend developers to use SparkPost's webhook (https://support.sparkpost.com/customer/portal/articles/1929974-defining-webhooks) to handle errors asynchronously.

Thanks

**Comment by dgoerlich** [comment]
We are no longer raising an exception - but a StandardError.  We made this change specifically so that we would be appropriately respecting the config.action_mailer.raise_delivery_errors = false setting.  Here's the related issue:

https://github.com/the-refinery/sparkpost_rails/issues/12

In your example, setting that action_mailer configuration should give you the effect you are seeking.
