### ISSUE TITLE
Email html content as text with multipart false option

### ISSUE THREAD

**Issue by Ashviniv** [the-refinery/sparkpost_rails#31]
Email with HTML content is delivered as plain text with HTML tags. 
Fixed it by changing `lib/sparkpost_rails/delivery_method.rb` But don't know whether it is the correct approach or not . #30

**Comment by BradyBonnette** [comment]
I believe this was fixed with 379364a28d1ca99ced30e87b01f96ff080642bae

@dgoerlich can you confirm or correct me if I am wrong? I think the difference here is the added SparkPost configuration option `html_content_only` meaning you have to specify a single message (or all of them with a default configuration) is HTML, otherwise they are sent as plain-text.

**Comment by dgoerlich** [comment]
Ah yes - that's correct @BradyBonnette.  @Ashviniv we do have support for HTML only through that configuration option.  You can set it on a per-transmission basis, or you can set it in the configuration so that all emails are sent that way.  See the bottom of this section of the readme:  https://github.com/the-refinery/sparkpost_rails#transmission-specific-settings
