### ISSUE TITLE
Can't send email to Multiple recipients

### ISSUE THREAD

**Issue by paritoshbotre** [the-refinery/sparkpost_rails#32]
I'm sending multiple email addresses but the problem i'm running into is that everyone in the "TO" list sees their email address there and others who are known to be supposed to be "TO" field are not getting the email because they don't see them there.

So there is way to display all "To" recipients ?

**Comment by kevinkimball** [comment]
@paritoshbotre this seems relevant: https://github.com/SparkPost/php-sparkpost/issues/66

**Comment by zenzei** [comment]
Hi, sorry but I think this change has introduce some wrong behaviour.

Right now if I try to send a non transactional email like
```
to = ['test1@gmail.com','test2@gmail.com']
mail(to: to_email, subject: "Test", body: "test", sparkpost_data: {campaign_id: 'Test', transactional: false})
```

Both receipients are seeing not only their emails but the other emails to. I don't want that. 

If I remove the header_to in the prepare_addresses the issue is fixed
```
    def prepare_addresses emails, names 
      emails = [emails] unless emails.is_a?(Array) 
      #header_to = emails.join(",") 
      #emails.each_with_index.map {|email, index| prepare_address(email, index, names, header_to) } 
      emails.each_with_index.map {|email, index| prepare_address(email, index, names, email) } 
    end 
```

Or maybe is just I'm using the api in a wrong way?

**Comment by zenzei** [comment]
Hi @paritoshbotre or @kevinkimball! Sorry to reask, did you saw this behaviour?

I don't want each receipient to see the others, and I'm not sure i'm using this in the right way. I don't want to display all "To" recipients, but that each receipient see only his/her email.

Thanks,

**Comment by jpaas** [comment]
I agree with @zenzei. I think this was not a great decision. Anyone using this list for non-transactional mailings are in for a really unpleasant surprise as we just discovered. 

Now I'm trying to figure out if there's any way to disable this behavior so that non-transactional recipients don't see all the other recipients. 

The safer thing to do would be to opt-in to revealing the other recipients.

**Comment by zenzei** [comment]
Hi @jpaas, if it helps what i have done is override the prepare_address in an initializer to rollback this behaviour.

```
module SparkPostRails 
  class DeliveryMethod

   private
    def prepare_address email, index, names, header_to
      #Rollback issue https://github.com/the-refinery/sparkpost_rails/issues/32, do not include all To  
      if !names[index].nil?
        #{ address:  { email: email, name: names[index], header_to: header_to } }
        { address:  { email: email, name: names[index] } }
      else  
        #{ address: { email: email, header_to: header_to } }
        { address: { email: email } } 
      end  
    end
    

  end
end
```


But the right thing to do would be adding some kind of option to choose before sending if the email of the others receipients should be seen or not.

**Comment by jpaas** [comment]
Thanks @zenzei. I already have to run a fork of this repo because of #41 , so I added something similar in my fork.
