### ISSUE TITLE
Rails 5.1 support

### ISSUE THREAD

**Issue by jpaas** [the-refinery/sparkpost_rails#41]
Could we please have an update to support Rails 5.1?

**Comment by superplussed** [comment]
Is this project abandoned?

**Comment by sman591** [comment]
Rails 5.1 "support" was sneaked in on #45: https://github.com/the-refinery/sparkpost_rails/pull/45/files#diff-cdb6282b5b0b660ba5cfbb2fe9cd7bfbR18. But there hasn't been a update to rubygems since last year's 1.4.0 release. 

All that should be needed is to release the 1.5.0 update that the [changelog mentions](https://github.com/the-refinery/sparkpost_rails/blob/master/CHANGELOG.md#150)... @dgoerlich ?

**Comment by TAiS46** [comment]
Hi there, we are also waiting for the update...

**Comment by nathanbertram** [comment]
+1 on getting this resolved

**Comment by TAiS46** [comment]
workaround: `gem 'sparkpost_rails', :git => 'git://github.com/the-refinery/sparkpost_rails.git'`

**Comment by nathanbertram** [comment]
Thanks :-) Yeah I got that working; I guess it just needs to be published to rubygems?

**Comment by TAiS46** [comment]
Yes, can we have this updated please? @dgoerlich

**Comment by cdesch** [comment]
Yeah, having issues with the gem. Not sure If we should rely on it
